version: '3'
services:
  
  my-tomcat:
    image: 'tomcat:9'
    ports:
    - '8081-8085:8080'
    volumes:
    - '/mnt/vol1:/usr/local/tomcat/webapps'

  mysql:
    image: mysql:5.7
    container_name: mysql_container
    environment:
      MYSQL_DATABASE: test
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin123
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
