version: '3'
services:
  
  my-tomcat:
    image: 'tomcat:9'
    ports:
    - '8081-8090:8080'
    volumes:
    - '/mnt/project-myapp/target/:/usr/local/tomcat/webapps'

 mysql:
    image: mysql:5.7
    container_name: mysql_container
    environment:
      MYSQL_DATABASE: test
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

